// <auto-generated />
using System;
using EasyCart.OrderApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EasyCart.OrderApi.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    partial class OrderDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EasyCart.OrderApi.Entities.Order", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("ClientId").HasColumnType("integer");
                b.Property<DateTime>("OrderDate").HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.ToTable("Orders");
            });

            modelBuilder.Entity("EasyCart.OrderApi.Entities.OrderItem", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                b.Property<int>("OrderId").HasColumnType("integer");
                b.Property<int>("ProductId").HasColumnType("integer");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<decimal>("UnitPrice").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                b.HasKey("Id");
                b.HasIndex("OrderId");
                b.ToTable("OrderItems");
            });

            modelBuilder.Entity("EasyCart.OrderApi.Entities.OrderItem", b =>
            {
                b.HasOne("EasyCart.OrderApi.Entities.Order", "Order")
                    .WithMany("Items")
                    .HasForeignKey("OrderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Order");
            });

            modelBuilder.Entity("EasyCart.OrderApi.Entities.Order", b =>
            {
                b.Navigation("Items");
            });
#pragma warning restore 612, 618
        }
    }
}
